version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./public:/var/www/html:Z
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:latest 
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db:Z
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - my-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

networks:
  my-network:
    driver: bridge


    # docker exec -it mongodb mongosh
    # docker exec -it web-php-1 bash
    # /etc/apache2/apache2.conf
    # ErrorDocument 404 /404.html

    # db.games.updateMany({}, {$set: {image_preview: "https://dummyimage.com/185x270/ced4da/6c757d.jpg"}});
    # ssh root@178.21.8.219